# port for the platform manager web server
port: 13200
login: eusas
password: hidden
# information about the information service
information_service_url: 149.156.10.253:11200
information_service_login: eusas
information_service_password: hidden
# credential for accessing node managers
node_manager_login: eusas
node_manager_password: hidden
# monitoring mongo db information <ip>:<port>
monitoring_db_url: 10.1.2.31:30000
monitoring_db_name: eusas_monitoring

# monitoring_db_login: eusas
# monitoring_db_password: hidden
